# Generated by Django 4.1.2 on 2022-10-17 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Wanted",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("title", models.CharField(max_length=200)),
                ("country", models.CharField(max_length=50)),
                ("location", models.CharField(max_length=50)),
                ("role", models.CharField(max_length=200)),
                ("reward", models.PositiveIntegerField(default=0)),
                ("tech_stack_name", models.CharField(max_length=200)),
                ("contents", models.TextField()),
                (
                    "company",
                    models.ForeignKey(
                        db_column="company_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company",
                        to="users.company",
                    ),
                ),
            ],
            options={
                "db_table": "wanted",
            },
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "applicant",
                    models.ForeignKey(
                        db_column="applicant_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applicant",
                        to="users.applicant",
                    ),
                ),
                (
                    "wanted",
                    models.ForeignKey(
                        db_column="wanted_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wanted",
                        to="apply.wanted",
                    ),
                ),
            ],
            options={
                "db_table": "application",
            },
        ),
    ]
